// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CustomerCustomerDemo
    {
        /// <summary>
        /// Initializes a new instance of the CustomerCustomerDemo class.
        /// </summary>
        public CustomerCustomerDemo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomerCustomerDemo class.
        /// </summary>
        public CustomerCustomerDemo(string customerId = default(string), string customerTypeId = default(string), Customer customer = default(Customer), CustomerDemographic customerType = default(CustomerDemographic))
        {
            CustomerId = customerId;
            CustomerTypeId = customerTypeId;
            Customer = customer;
            CustomerType = customerType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerTypeId")]
        public string CustomerTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Customer")]
        public Customer Customer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerType")]
        public CustomerDemographic CustomerType { get; set; }

    }
}
