// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmployeeTerritory
    {
        /// <summary>
        /// Initializes a new instance of the EmployeeTerritory class.
        /// </summary>
        public EmployeeTerritory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmployeeTerritory class.
        /// </summary>
        public EmployeeTerritory(int? employeeId = default(int?), string territoryId = default(string), Employee employee = default(Employee), Territory territory = default(Territory))
        {
            EmployeeId = employeeId;
            TerritoryId = territoryId;
            Employee = employee;
            Territory = territory;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeId")]
        public int? EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TerritoryId")]
        public string TerritoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Employee")]
        public Employee Employee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Territory")]
        public Territory Territory { get; set; }

    }
}
