// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Employee
    {
        /// <summary>
        /// Initializes a new instance of the Employee class.
        /// </summary>
        public Employee()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Employee class.
        /// </summary>
        public Employee(int? employeeId = default(int?), string lastName = default(string), string firstName = default(string), string title = default(string), string titleOfCourtesy = default(string), System.DateTime? birthDate = default(System.DateTime?), System.DateTime? hireDate = default(System.DateTime?), string address = default(string), string city = default(string), string region = default(string), string postalCode = default(string), string country = default(string), string homePhone = default(string), string extension = default(string), byte[] photo = default(byte[]), string notes = default(string), int? reportsTo = default(int?), string photoPath = default(string), Employee reportsToNavigation = default(Employee), IList<EmployeeTerritory> employeeTerritories = default(IList<EmployeeTerritory>), IList<Employee> inverseReportsToNavigation = default(IList<Employee>), IList<Order> orders = default(IList<Order>))
        {
            EmployeeId = employeeId;
            LastName = lastName;
            FirstName = firstName;
            Title = title;
            TitleOfCourtesy = titleOfCourtesy;
            BirthDate = birthDate;
            HireDate = hireDate;
            Address = address;
            City = city;
            Region = region;
            PostalCode = postalCode;
            Country = country;
            HomePhone = homePhone;
            Extension = extension;
            Photo = photo;
            Notes = notes;
            ReportsTo = reportsTo;
            PhotoPath = photoPath;
            ReportsToNavigation = reportsToNavigation;
            EmployeeTerritories = employeeTerritories;
            InverseReportsToNavigation = inverseReportsToNavigation;
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeId")]
        public int? EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TitleOfCourtesy")]
        public string TitleOfCourtesy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BirthDate")]
        public System.DateTime? BirthDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HireDate")]
        public System.DateTime? HireDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public string PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HomePhone")]
        public string HomePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Extension")]
        public string Extension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Photo")]
        public byte[] Photo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Notes")]
        public string Notes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReportsTo")]
        public int? ReportsTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhotoPath")]
        public string PhotoPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReportsToNavigation")]
        public Employee ReportsToNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeTerritories")]
        public IList<EmployeeTerritory> EmployeeTerritories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InverseReportsToNavigation")]
        public IList<Employee> InverseReportsToNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Orders")]
        public IList<Order> Orders { get; set; }

    }
}
