// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Order
    {
        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order(int? orderId = default(int?), string customerId = default(string), int? employeeId = default(int?), System.DateTime? orderDate = default(System.DateTime?), System.DateTime? requiredDate = default(System.DateTime?), System.DateTime? shippedDate = default(System.DateTime?), int? shipVia = default(int?), double? freight = default(double?), string shipName = default(string), string shipAddress = default(string), string shipCity = default(string), string shipRegion = default(string), string shipPostalCode = default(string), string shipCountry = default(string), Customer customer = default(Customer), Employee employee = default(Employee), Shipper shipViaNavigation = default(Shipper), IList<OrderDetail> orderDetails = default(IList<OrderDetail>))
        {
            OrderId = orderId;
            CustomerId = customerId;
            EmployeeId = employeeId;
            OrderDate = orderDate;
            RequiredDate = requiredDate;
            ShippedDate = shippedDate;
            ShipVia = shipVia;
            Freight = freight;
            ShipName = shipName;
            ShipAddress = shipAddress;
            ShipCity = shipCity;
            ShipRegion = shipRegion;
            ShipPostalCode = shipPostalCode;
            ShipCountry = shipCountry;
            Customer = customer;
            Employee = employee;
            ShipViaNavigation = shipViaNavigation;
            OrderDetails = orderDetails;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderId")]
        public int? OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeId")]
        public int? EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderDate")]
        public System.DateTime? OrderDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequiredDate")]
        public System.DateTime? RequiredDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShippedDate")]
        public System.DateTime? ShippedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipVia")]
        public int? ShipVia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Freight")]
        public double? Freight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipName")]
        public string ShipName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipAddress")]
        public string ShipAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipCity")]
        public string ShipCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipRegion")]
        public string ShipRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipPostalCode")]
        public string ShipPostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipCountry")]
        public string ShipCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Customer")]
        public Customer Customer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Employee")]
        public Employee Employee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipViaNavigation")]
        public Shipper ShipViaNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderDetails")]
        public IList<OrderDetail> OrderDetails { get; set; }

    }
}
