// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Region
    {
        /// <summary>
        /// Initializes a new instance of the Region class.
        /// </summary>
        public Region()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Region class.
        /// </summary>
        public Region(int? regionId = default(int?), string regionDescription = default(string), IList<Territory> territories = default(IList<Territory>))
        {
            RegionId = regionId;
            RegionDescription = regionDescription;
            Territories = territories;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegionId")]
        public int? RegionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegionDescription")]
        public string RegionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Territories")]
        public IList<Territory> Territories { get; set; }

    }
}
