// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Shipper
    {
        /// <summary>
        /// Initializes a new instance of the Shipper class.
        /// </summary>
        public Shipper()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Shipper class.
        /// </summary>
        public Shipper(int? shipperId = default(int?), string companyName = default(string), string phone = default(string), IList<Order> orders = default(IList<Order>))
        {
            ShipperId = shipperId;
            CompanyName = companyName;
            Phone = phone;
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipperId")]
        public int? ShipperId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompanyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Orders")]
        public IList<Order> Orders { get; set; }

    }
}
