// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Territory
    {
        /// <summary>
        /// Initializes a new instance of the Territory class.
        /// </summary>
        public Territory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Territory class.
        /// </summary>
        public Territory(string territoryId = default(string), string territoryDescription = default(string), int? regionId = default(int?), Region region = default(Region), IList<EmployeeTerritory> employeeTerritories = default(IList<EmployeeTerritory>))
        {
            TerritoryId = territoryId;
            TerritoryDescription = territoryDescription;
            RegionId = regionId;
            Region = region;
            EmployeeTerritories = employeeTerritories;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TerritoryId")]
        public string TerritoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TerritoryDescription")]
        public string TerritoryDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegionId")]
        public int? RegionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Region")]
        public Region Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeTerritories")]
        public IList<EmployeeTerritory> EmployeeTerritories { get; set; }

    }
}
